// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgD_Z8JUxbg4n9BlHZ372Z09q5ArLZgw',
    appId: '1:170637405271:web:2f68c70daefbfed970c712',
    messagingSenderId: '170637405271',
    projectId: 'safe-her-app-498605',
    authDomain: 'safe-her-app-498605.firebaseapp.com',
    databaseURL: 'https://safe-her-app-498605-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-her-app-498605.firebasestorage.app',
    measurementId: 'G-4CFC0PQ9CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhj1S39N5DufZXi-I_dPNKcgaz7QoFjpw',
    appId: '1:170637405271:android:e1594010a2bd877370c712',
    messagingSenderId: '170637405271',
    projectId: 'safe-her-app-498605',
    databaseURL: 'https://safe-her-app-498605-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-her-app-498605.firebasestorage.app',
  );

}